name: workflow-experiments

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "some_var=sOmE-vAlU3" >> $GITHUB_ENV
        shell: bash

  job_2:
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ env.some_var }}"

